name: Serious Think
description: Keep low profile, he said, keep low profile.
meta_description: "c/c++/linux/java/android/ios/mac/windows"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://serious-think.me'
google_analytics: 'UA-XXXXXXXX-X'
disqus: true 
disqus_shortname: 'cy198706'

# Details for the RSS feed generator
url:            'http://serious-think.me'
author:         'serious'
authorTwitter:  'serious008'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
