


# Site settings Update for my Blog : spaceg.github.io Mo. 4.Mai 2015 - Weed - 15.49:24 2015 
title: serious-think
email: cy198706@gmail.com
description: "Keep low profile, he said, keep low profile."
baseurl: ""
url: "https://serious-think.me"
twitter_username: serious008
github_username:  serious198706
google_username:  https://plus.google.com/101826267816845608605/posts


# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

paginate: 5 #posts per page



compress_html:
  clippings: [div, p, ul, td, h1, h2]
  comments: []
  endings: []
  ignore:
    envs: []



